#!/bin/bash

# Script to set up binary links and verify tool availability

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_BIN="${SCRIPT_DIR}/bin"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "Setting up binary links..."

# Create bin directory if it doesn't exist
mkdir -p "${TOOLS_BIN}"

# Function to create tool wrapper
create_wrapper() {
    local tool_name=$1
    local actual_binary=$2
    local wrapper_path="${TOOLS_BIN}/${tool_name}"
    
    cat > "$wrapper_path" << EOF
#!/bin/bash
# Wrapper script for ${tool_name}
exec "${actual_binary}" "\$@"
EOF
    
    chmod +x "$wrapper_path"
    echo "Created wrapper: $wrapper_path"
}

# Function to find and link tool
find_and_link_tool() {
    local tool_name=$1
    local search_patterns=("$@")
    
    echo "Searching for ${tool_name}..."
    
    # Remove tool name from array
    unset 'search_patterns[0]'
    
    # Search in various locations
    for pattern in "${search_patterns[@]}"; do
        # Check in tools directory
        local found=$(find "${SCRIPT_DIR}" -name "$pattern" -type f -executable 2>/dev/null | head -1)
        
        if [[ -n "$found" ]]; then
            echo "Found: $found"
            if [[ ! -e "${TOOLS_BIN}/${tool_name}" ]]; then
                ln -sf "$found" "${TOOLS_BIN}/${tool_name}"
                echo "Linked to: ${TOOLS_BIN}/${tool_name}"
            fi
            return 0
        fi
        
        # Check system path
        if command -v "$pattern" &> /dev/null; then
            local system_path=$(which "$pattern")
            echo "Found in system: $system_path"
            create_wrapper "$tool_name" "$system_path"
            return 0
        fi
    done
    
    echo "Warning: ${tool_name} not found"
    return 1
}

# Link all tools
echo "Linking ncnn-vulkan tools..."
find_and_link_tool "waifu2x-ncnn-vulkan" "waifu2x-ncnn-vulkan"
find_and_link_tool "srmd-ncnn-vulkan" "srmd-ncnn-vulkan"
find_and_link_tool "realsr-ncnn-vulkan" "realsr-ncnn-vulkan"
find_and_link_tool "realcugan-ncnn-vulkan" "realcugan-ncnn-vulkan"
find_and_link_tool "rife-ncnn-vulkan" "rife-ncnn-vulkan"
find_and_link_tool "cain-ncnn-vulkan" "cain-ncnn-vulkan"
find_and_link_tool "dain-ncnn-vulkan" "dain-ncnn-vulkan"

echo ""
echo "Linking other tools..."
find_and_link_tool "Anime4KCPP" "Anime4KCPP" "Anime4KCPP_CLI"
find_and_link_tool "waifu2x-converter-cpp" "waifu2x-converter-cpp"

# Check for FFmpeg
echo ""
echo "Checking system tools..."
find_and_link_tool "ffmpeg" "ffmpeg"
find_and_link_tool "ffprobe" "ffprobe"

# Generate tool availability report
echo ""
echo "Generating tool availability report..."

cat > "${TOOLS_BIN}/tool_availability.txt" << EOF
Tool Availability Report
Generated: $(date)
========================

Binary Directory: ${TOOLS_BIN}

Tools Status:
EOF

# Check each tool
for tool in waifu2x-ncnn-vulkan srmd-ncnn-vulkan realsr-ncnn-vulkan \
            realcugan-ncnn-vulkan rife-ncnn-vulkan cain-ncnn-vulkan \
            dain-ncnn-vulkan Anime4KCPP waifu2x-converter-cpp \
            ffmpeg ffprobe; do
    
    if [[ -e "${TOOLS_BIN}/${tool}" ]]; then
        echo "✓ ${tool}: Available" >> "${TOOLS_BIN}/tool_availability.txt"
    else
        echo "✗ ${tool}: Not found" >> "${TOOLS_BIN}/tool_availability.txt"
    fi
done

echo "" >> "${TOOLS_BIN}/tool_availability.txt"
echo "Path Configuration:" >> "${TOOLS_BIN}/tool_availability.txt"
echo "Add the following to your shell configuration to use these tools:" >> "${TOOLS_BIN}/tool_availability.txt"
echo "export PATH=\"${TOOLS_BIN}:\$PATH\"" >> "${TOOLS_BIN}/tool_availability.txt"

# Display report
cat "${TOOLS_BIN}/tool_availability.txt"

# Create Qt integration config
echo ""
echo "Creating Qt integration configuration..."

cat > "${PROJECT_ROOT}/SRC_v3.41.01-beta/Waifu2x-Extension-QT/binary_paths.pri" << EOF
# Binary paths configuration for Waifu2x-Extension-GUI
# Auto-generated by setup_binary_links.sh

DEFINES += EXTERNAL_TOOLS_PATH=\\"$$PWD/../../tools/bin\\"

# Tool binary definitions
DEFINES += WAIFU2X_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/waifu2x-ncnn-vulkan\\"
DEFINES += SRMD_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/srmd-ncnn-vulkan\\"
DEFINES += REALSR_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/realsr-ncnn-vulkan\\"
DEFINES += REALCUGAN_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/realcugan-ncnn-vulkan\\"
DEFINES += RIFE_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/rife-ncnn-vulkan\\"
DEFINES += CAIN_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/cain-ncnn-vulkan\\"
DEFINES += DAIN_NCNN_VULKAN_PATH=\\"$$PWD/../../tools/bin/dain-ncnn-vulkan\\"
DEFINES += ANIME4KCPP_PATH=\\"$$PWD/../../tools/bin/Anime4KCPP\\"
DEFINES += WAIFU2X_CONVERTER_CPP_PATH=\\"$$PWD/../../tools/bin/waifu2x-converter-cpp\\"
EOF

echo "Qt configuration created: binary_paths.pri"
echo ""
echo "Setup completed!"